---
title: "Descriptive statistics of Paridae monitoring data"
author: "Freya Coursey"
format: html
editor: visual
---

## Load packages

```{r}
#| label: Load Packages
# Core packages for data manipulation, visualization, and modeling
library(dplyr)       # Data manipulation
library(ggplot2)     # Visualization
library(lme4)        # Mixed-effects models
library(broom.mixed) # Tidy methods for mixed models
library(TMB)         # Template Model Builder
library(MuMIn)       # Model selection and multimodel inference

# Visualization and theme extensions
library(ggfortify)   # Auto-plotting for statistical results
library(ggiraphExtra) # Interactive ggplot extensions
library(ggthemes)    # Additional themes for ggplot2

# Model interpretation and effects
library(effects)     # Visualizing model effects
library(car)         # Companion to Applied Regression
library(jtools)      # Tools for regression models

# Additional data handling and formatting
library(tidyr)       # Data tidying
library(Hmisc)       # Miscellaneous data utilities
library(pander)      # Rendering tables in markdown
library(usethis)
library(conflicted)

conflict_prefer_all("dplyr", quiet = TRUE) # use dplyr if there is a name conflict

# default plot theme
theme_set(theme_classic())
```

## Load data

(from local drive for now...)

```{r}
#| label: Load data
#| 
Main_data_milde <- read.csv("~/Documents/Documents - Freya's Macbook Pro/PhD/PhD Research/Monitoring_R_project/Main_data_milde.csv")
View(Main_data_milde)
```

## Data Analysis

Data were analysed in R version r paste(R.version$major, R.version$minor, sep = ".") [@R], using tidyverse for data manipulation and plots [@tidyverse].

```{r}
#| label: Clean and filter data

# File name for cleaning
Nestbox_data <- Main_data_milde

# Covariate to factor
Nestbox_data$Year<-factor(Nestbox_data$Year)
Nestbox_data$Nestbox<-factor(Nestbox_data$Nestbox)
Nestbox_data$Species<-factor(Nestbox_data$Species)

# Factor to covariate
Nestbox_data$LayDate <- as.numeric(as.character(Nestbox_data$LayDate))
Nestbox_data$BroodSize <- as.numeric(as.character(Nestbox_data$BroodSize))
Nestbox_data$Fledged <- as.numeric(as.character(Nestbox_data$Fledged))
Nestbox_data$ClutchSize <- as.numeric(as.character(Nestbox_data$ClutchSize))
Nestbox_data$Hatch_gap <- as.numeric(as.character(Nestbox_data$Hatch_gap))

# Subsetting data by species
BT.data<-subset(Nestbox_data, Species=="Blåmeis")
GT.data<-subset(Nestbox_data, Species=="Kjøttmeis")

```

The `echo: false` option disables the printing of code (only output is displayed).
